apiVersion: apps/v1
kind: Deployment
metadata:
  name: kdemo
  labels:
    app: kdemo
  annotations:
    field.knot8.io/audience: /spec/template/spec/containers/~{"name":"app"}/env/~{"name":"KDEMO_AUDIENCE"}/value
    knot8.io/original: |
      audience: Kubernetes
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kdemo
  template:
    metadata:
      labels:
        app: kdemo
    spec:
      containers:
      - name: app
        image: mkmik/kdemo-cbce88c499ad59d7a42a0d7bcf9456f0@sha256:7948845e3f467e25e9b9a2fcbc0272e33c4c89e0e53bc51c0eb309d0aff6b9b2
        env:
        - name: KDEMO_AUDIENCE
          value: Knot8
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: kdemo
spec:
  selector:
    app: kdemo
  ports:
  - port: 8080
    targetPort: 8080

---
